name: weather-api
services:
  db:
    image: postgres:17.5
    container_name: db
    env_file:
      - .env
    volumes:
      - ./db-data/prod:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - weather-api-network
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:8.0
    container_name: redis
    env_file:
      - .env
    ports:
      - 6379:6379
    networks:
      - weather-api-network
    volumes:
      - ./redis-data/prod:/data
    restart: always
    command:
      [
        "redis-server",
        "--appendonly",
        "yes",
        "--maxmemory",
        "512mb",
        "--maxmemory-policy",
        "noeviction",
      ]
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    container_name: api
    env_file:
      - .env
    ports:
      - 8000:8000
    networks:
      - weather-api-network
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: ["npm", "run", "start"]

networks:
  weather-api-network:
    driver: bridge
